### ISSUE TITLE
product.php

### ISSUE THREAD

**Issue by ogasukegit** [windresistance/andC#88]
would it be possible to switch off modal window below 1023 pixels? 
cause the modal-image is too big and won't fit on the screen

**Comment by antoine-boue** [comment]
So below 1023px, it should not be possible to display the modal (by clicking on the slider) ?
May I ask why 1023px ? Is it because the image width is 1000px? So the images width will always be 1000px?
Because for example if another image of a product is like 1200px, the modal-image will be too big again.

**Comment by ogasukegit** [comment]
because i pad pro is 1024px. does that make sense? it's true that if the images are bigger than 1024px the modal-image will be too big again. would it possible to set the modal-image wou't be bigger than 1000px? like max-width: 1000px? 
if it takes too much time, then don't need to do it. they don't put any other images on this page anyway.

**Comment by antoine-boue** [comment]
I think the best way is putting a max width of 100%, so that the image will never be bigger than screen, and will reduce if the screen is smaller? What do you think ?

**Comment by ogasukegit** [comment]
yeah that sounds great! lets do it in that way if it's okay for you!
thanks!
